homework1
NastyBoget/afina pull request #1
Opened 2020-03-03 15:33 UTC by NastyBoget

2020-03-06 17:23 UTC, Fen99 reviewed
clang-format

2020-03-06 17:23 UTC, Fen99 commented on src/storage/SimpleLRU.cpp
> +	while (key.size() + value.size()  + _cur_size > _max_size) {
Если элемент уже есть, то это слишком жесткое условие (нужно на разность curr_value.size() - new_value.size())

2020-03-06 17:23 UTC, Fen99 commented on src/storage/SimpleLRU.h
> +    lru_node *_lru_tail;
Указатель на константу?

2020-03-06 17:23 UTC, Fen99 commented on src/storage/SimpleLRU.cpp
> +        _lru_index.insert({std::reference_wrapper<const std::string>(new_node->key),
emplace?

2020-03-06 17:23 UTC, Fen99 commented on src/storage/SimpleLRU.cpp
> +bool SimpleLRU::PutIfAbsent(const std::string &key, const std::string &value) {
Нужно вынести общий код Put и PutIfAbsent в общую функцию

2020-03-12 13:39 UTC, Fen99 requested changes
Прошу прощения, не заметил еще 1 замечание

2020-03-12 13:39 UTC, Fen99 commented on src/storage/SimpleLRU.cpp
> +        delete_oldest_node();
Здесь (и в других аналогичных местах) можно случайно удалить it

2020-03-29 13:28 UTC, Fen99 commented on src/storage/SimpleLRU.cpp
> +        delete_oldest_node();
Можно просто сначала сделать move_to_tail

2020-03-29 13:32 UTC, Fen99 requested changes

2020-03-29 13:32 UTC, Fen99 commented on src/storage/SimpleLRU.h
> +    lru_node *const _lru_tail = new lru_node;
А точно нужно new использовать? И не вижу delete к нему.
Возможно, я был неправ про указатель на константу - нужно же менять предыдущий.

2020-03-29 13:48 UTC, NastyBoget commented on src/storage/SimpleLRU.h
> +    lru_node *const _lru_tail = new lru_node;
delete не нужен, так как в предыдущем есть std::unique_ptr от _lru_tail, удаление осуществится автоматически.

2020-04-12 17:25 UTC, merged